### PR TITLE
check for undefined target

### PR DESCRIPTION
**Pull request by amihaiemil**
PR for #4 
Check if the target element is present on the page to prevent error.
Wrapped the inside/outside check and handler call in:
```javascript
if(targetElement != undefined) {
//...
}
```

### CODE REVIEW

**Comment by amihaiemil** [comment]
@gajus Can you check this PR? :D

**Comment by amihaiemil** [comment]
@gajus ping :) can you accept and release if it's ok, I would really like to solve this issue :D

**Comment by gajus** [comment]
https://github.com/gajus/react-outside-event/tree/v1.2.5

**Comment by gajus** [comment]
Thank you

**Pull request merged**
